
# Config for running e-commerce-intro Cloud Formation Templates. 
# Includes ECR, Codebuild and Frontend

REGION="us-east-1" # UPDATE to reflect the user's preferred region
STACK_PREFIX="e-commerce-cicd"

RUN_ECR_BOOTSTRAP=true
RUN_NETWORKING=true
PUSH_INITIAL_IMAGES=true

# Local path to current each microservice. Needed for the initial push to ECR
INITIAL_IMAGE_SERVICES=(
  "orders:<Path to Orders Repo>"
  "users:<Path to Users Repo>"
  "products:<Path to Products Repo>"
)

# Anything main-stack.yaml needs beyond the 3 image URIs (which the script fills in automatically)
EXTRA_PARAM_OVERRIDES=(
  DBUsername=dbadmin
)