
# Config for running e-commerce-intro Cloud Formation Templates. 
# Includes ECR, Codebuild and Frontend

REGION="us-east-1" # UPDATE to reflect the user's preferred region
STACK_PREFIX="e-commerce-cicd"

RUN_ECR_BOOTSTRAP=true
RUN_NETWORKING=true
PUSH_INITIAL_IMAGES=true

# Local path to current each microservice. Needed for the initial push to ECR
INITIAL_IMAGE_SERVICES=(
  "orders:/Users/adrianprado/Developer/aws-curriculum/ada-e-commerce/Ada-E-Commerce-Orders-Service"
  "users:/Users/adrianprado/Developer/aws-curriculum/ada-e-commerce/Ada-E-Commerce-User-Service"
  "products:/Users/adrianprado/Developer/aws-curriculum/ada-e-commerce/Ada-E-Commerce-Product-Service"
)

# Anything main-stack.yaml needs beyond the 3 image URIs (which the script fills in automatically)
EXTRA_PARAM_OVERRIDES=(
  DBUsername=dbadmin
)