
# Config for running e-commerce-intro Cloud Formation Templates. 
# Includes ECR, Codebuild and Frontend

REGION="us-east-1" # UPDATE to reflect the user's preferred region
STACK_PREFIX="e-commerce-iam"

RUN_ECR_BOOTSTRAP=true
RUN_CODEBUILD=true
RUN_FRONTEND=true

GITHUB_BRANCH="deploy-lab-branch"
FRONTEND_BRANCH="main"
ORDERS_REPO_GIT_URL="https://github.com/Ada-Activities/Ada-E-Commerce-Orders-Service"
USERS_REPO_GIT_URL="https://github.com/Ada-Activities/Ada-E-Commerce-User-Service"
PRODUCTS_REPO_GIT_URL="https://github.com/Ada-Activities/Ada-E-Commerce-Product-Service"
FRONTEND_REPO_GIT_URL="https://github.com/Ada-Activities/Ada-E-Commerce-FE"
FRONTEND_BUILD_OUTPUT_DIR="dist"   # Vite Frontend uses "dist", CRA frontend would use "build"

# Anything main-stack.yaml needs beyond the 3 image URIs (which the script fills in automatically)
EXTRA_PARAM_OVERRIDES=(
  VpcId=vpc-xxxxxxxxx #UPDATE to default vpc in user's preferred region
  SubnetIds=subnet-xxxxxxxxx,subnet-xxxxxxx #UPDATE to two different subnets in the default vpc in user's preferred region
  DBUsername=dbadmin
  GitHubBranch="$GITHUB_BRANCH"
)
